### ISSUE TITLE
Unity scene generates only partial map

### ISSUE THREAD

**Issue by arttukataja** [marian42/wavefunctioncollapse#8]
Opening the scene and pressing play generates only partial level and the player drops through the world:

![image](https://user-images.githubusercontent.com/2311688/48974216-74142400-f05a-11e8-8cec-122f7f05ba8a.png)

Should I do some preparation in Unity with maybe the "Create module data" or "Initialize" buttons or is the scene somehow broken?

Thanks a lot for creating this beautiful project!

**Comment by marian42** [comment]
Sorry you're having problems. You don't need to use any buttons. I just cloned the project from scratch, opened the scene, pressed Play and it worked.

Did you get any warnings or errors when you opened the project?  
Can you check if any of the children of the Prototypes node have MeshRenderers with missing meshes?
Do you have Blender installed on your PC?

**Comment by kungfooman** [comment]
I just had the same problem, the MeshRenderers had missing meshes, could fix it via:

1) open `Assets\blocks.blend` in Blender 2.79
2) disable all "eyes" in the hierarchy (only three nodes for the tower clock)
3) save it (ctrl+s and mouse click)
4) Unity should reload the blend file
5) press play
6) should work

I don't know if disabling the visibility is needed or just the "save blend file" to trigger Unity to reimport

**Comment by arttukataja** [comment]
That did the trick kungfooman!

I just installed Blender, opened blocks.blend and saved the file and that was it.

A big thank you to both of you :)

**Comment by jak2030** [comment]
Even after saving in Blender, I see the same 'partial' map issue: 

<img width="1150" alt="Screen Shot 2019-07-02 at 6 06 41 PM" src="https://user-images.githubusercontent.com/1641058/60531999-2c423300-9cf4-11e9-9170-7ed526a1b648.png">

It definitely seems like certain pieces of the mesh are simply not visible - the player seems to collide with invisible boundaries when moving around, and you can see the slots assembling on multiple vertical levels:

<img width="1136" alt="Screen Shot 2019-07-02 at 6 09 13 PM" src="https://user-images.githubusercontent.com/1641058/60532185-9f4ba980-9cf4-11e9-87e3-50bced8653f4.png">

Any guesses or intuition about what other reasons might cause this would be greatly appreciated!

**Comment by marian42** [comment]
What do you see in the Prototypes scene? I assume that some prototypes have meshes while others dont't. Can you confirm this?

There was a problem that looked like your screenshot, but it was fixed a while ago. Can you confirm that you're on the latest commit (it doesn't matter if you pulled the changes from today).

The invisible walls appear because the colliders are created directly in Unity and are thus imported correctly. Only the visual mesh is missing, everything else is there.

Please do the following:

1. Delete all project files
2. Use git clone to download the project again
3. Open blocks.blend in Blender and save it (like you did to get the screenshot above)
4. Open the project in Unity and check if this solved it

If the problem persists, you can do this:

1. Open the Prototypes scene
2. Edit the Prototypes prefab
3. Look for modules with missing meshes. In the `MeshFilter` component, it should say something like "Interior door (missing)". Click on the circle next to it, search for the name (like "Interior door") and select the mesh.

If you can fix the meshes like this, they will appear in the game again.

**Comment by jak2030** [comment]
Apologies for the slow response - back on the grid and looking to work with your project again! FWIW, it seems that manually updating `MeshFilter` assignments in the `Prototype` scene works, but I switched over to a Windows machine and everything works perfectly there, so going to proceed on that tack!

Thanks again for your thorough help and advice.
